apiVersion: v1
kind: Namespace
metadata:
  name: devops-musyaffadli
---
apiVersion: v1
kind: Secret
metadata:
  name: cilist-secret
  namespace: devops-musyaffadli
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: cGFzc3dvcmQ=
  DB_SELECT: cGVvcGxl
  DB_ENDPOINT: Y2lsaXN0LWRiLmNhaDR6ZW9kdXZpMi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-be
  namespace: devops-musyaffadli
data:
  BASE_URL_PORT: "5000"
  DATABASE_PORT: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-be-svc
  namespace: devops-musyaffadli
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - nodePort: 30100
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cilist
    tier: backend
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-be
  namespace: devops-musyaffadli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilist
      tier: backend
  template:
    metadata:
      labels:
        app: cilist
        tier: backend
    spec:
      #volumes:
      #- name: configmap-be
      #  configMap:
      #    name: configmap-be
      containers:
      - image: ravennaras/cilist:bejenkins
        name: cilist-be
        ports:
        - containerPort: 5000
        #volumeMounts:
        #- name: configmap-be
        #  mountPath: "/"
        #  subPath: ".env"
        env:
        - name: BASE_URL_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-be
              key: BASE_URL_PORT
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-be
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_PASS
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_ENDPOINT
        - name: DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_SELECT
      restartPolicy: Always