apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fe
  namespace: devops-musyaffadli
data:
    #REACT_APP_BACKEND_URL: "cilist-be-svc.devops-musyaffadli.svc.cluster.local:5000"
    #REACT_APP_BACKEND_URL: "cilist-be-svc:5000"
    REACT_APP_BACKEND_URL: "http://ec2-44-200-9-151.compute-1.amazonaws.com:30100" 
