apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-svc
  namespace: devops-musyaffadli
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cilist
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
