apiVersion: v1
kind: Secret
metadata:
  name: cilist-secret
  namespace: devops-musyaffadli
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: cGFzc3dvcmQ=
  DB_SELECT: cGVvcGxl
  DB_ENDPOINT: Y2lsaXN0LWRiLmNhaDR6ZW9kdXZpMi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
